# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw/annotations.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(306, 387)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameEdit.sizePolicy().hasHeightForWidth())
        self.nameEdit.setSizePolicy(sizePolicy)
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout_2.addWidget(self.nameEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.typeLabel = QtWidgets.QLabel(Dialog)
        self.typeLabel.setObjectName("typeLabel")
        self.horizontalLayout.addWidget(self.typeLabel)
        self.typeBox = QtWidgets.QComboBox(Dialog)
        self.typeBox.setObjectName("typeBox")
        self.horizontalLayout.addWidget(self.typeBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.foregroundCheck = QtWidgets.QCheckBox(self.page)
        self.foregroundCheck.setObjectName("foregroundCheck")
        self.horizontalLayout_15.addWidget(self.foregroundCheck)
        self.foregroundColorButton = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foregroundColorButton.sizePolicy().hasHeightForWidth())
        self.foregroundColorButton.setSizePolicy(sizePolicy)
        self.foregroundColorButton.setMinimumSize(QtCore.QSize(30, 0))
        self.foregroundColorButton.setMaximumSize(QtCore.QSize(45, 40))
        self.foregroundColorButton.setText("")
        self.foregroundColorButton.setObjectName("foregroundColorButton")
        self.horizontalLayout_15.addWidget(self.foregroundColorButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.highlightCheck = QtWidgets.QCheckBox(self.page)
        self.highlightCheck.setObjectName("highlightCheck")
        self.horizontalLayout_16.addWidget(self.highlightCheck)
        self.highlightColorButton = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.highlightColorButton.sizePolicy().hasHeightForWidth())
        self.highlightColorButton.setSizePolicy(sizePolicy)
        self.highlightColorButton.setMinimumSize(QtCore.QSize(30, 24))
        self.highlightColorButton.setMaximumSize(QtCore.QSize(45, 40))
        self.highlightColorButton.setText("")
        self.highlightColorButton.setObjectName("highlightColorButton")
        self.horizontalLayout_16.addWidget(self.highlightColorButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.boldCheck = QtWidgets.QCheckBox(self.page)
        self.boldCheck.setObjectName("boldCheck")
        self.horizontalLayout_17.addWidget(self.boldCheck)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.italicCheck = QtWidgets.QCheckBox(self.page)
        self.italicCheck.setObjectName("italicCheck")
        self.horizontalLayout_18.addWidget(self.italicCheck)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.underlineCheck = QtWidgets.QCheckBox(self.page)
        self.underlineCheck.setObjectName("underlineCheck")
        self.horizontalLayout_19.addWidget(self.underlineCheck)
        self.underlineType = QtWidgets.QComboBox(self.page)
        self.underlineType.setObjectName("underlineType")
        self.horizontalLayout_19.addWidget(self.underlineType)
        self.underlineColorButton = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.underlineColorButton.sizePolicy().hasHeightForWidth())
        self.underlineColorButton.setSizePolicy(sizePolicy)
        self.underlineColorButton.setMinimumSize(QtCore.QSize(45, 24))
        self.underlineColorButton.setMaximumSize(QtCore.QSize(45, 40))
        self.underlineColorButton.setText("")
        self.underlineColorButton.setObjectName("underlineColorButton")
        self.horizontalLayout_19.addWidget(self.underlineColorButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_3.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Annotation Editor"))
        self.nameEdit.setPlaceholderText(_translate("Dialog", "Annotation Name"))
        self.typeLabel.setText(_translate("Dialog", "Type"))
        self.foregroundCheck.setText(_translate("Dialog", "Foreground"))
        self.highlightCheck.setText(_translate("Dialog", "Highlight"))
        self.boldCheck.setText(_translate("Dialog", "Bold"))
        self.italicCheck.setText(_translate("Dialog", "Italic"))
        self.underlineCheck.setText(_translate("Dialog", "Underline"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))

