# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw/settings.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1088, 612)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.treeViewPage = QtWidgets.QWidget()
        self.treeViewPage.setObjectName("treeViewPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.treeViewPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.treeView = QtWidgets.QTreeView(self.treeViewPage)
        self.treeView.setObjectName("treeView")
        self.gridLayout_5.addWidget(self.treeView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.treeViewPage)
        self.switchPage = QtWidgets.QWidget()
        self.switchPage.setObjectName("switchPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.switchPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.switchPage)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.refreshLibrary = QtWidgets.QCheckBox(self.groupBox)
        self.refreshLibrary.setObjectName("refreshLibrary")
        self.horizontalLayout_4.addWidget(self.refreshLibrary)
        self.fileRemember = QtWidgets.QCheckBox(self.groupBox)
        self.fileRemember.setObjectName("fileRemember")
        self.horizontalLayout_4.addWidget(self.fileRemember)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.coverShadows = QtWidgets.QCheckBox(self.groupBox)
        self.coverShadows.setObjectName("coverShadows")
        self.horizontalLayout_3.addWidget(self.coverShadows)
        self.performCulling = QtWidgets.QCheckBox(self.groupBox)
        self.performCulling.setObjectName("performCulling")
        self.horizontalLayout_3.addWidget(self.performCulling)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.darkIconsRadio = QtWidgets.QRadioButton(self.groupBox)
        self.darkIconsRadio.setObjectName("darkIconsRadio")
        self.horizontalLayout_7.addWidget(self.darkIconsRadio)
        self.lightIconsRadio = QtWidgets.QRadioButton(self.groupBox)
        self.lightIconsRadio.setObjectName("lightIconsRadio")
        self.horizontalLayout_7.addWidget(self.lightIconsRadio)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.autoTags = QtWidgets.QCheckBox(self.groupBox)
        self.autoTags.setObjectName("autoTags")
        self.horizontalLayout_9.addWidget(self.autoTags)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.switchPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.hideScrollBars = QtWidgets.QCheckBox(self.groupBox_2)
        self.hideScrollBars.setObjectName("hideScrollBars")
        self.horizontalLayout_6.addWidget(self.hideScrollBars)
        self.cachingEnabled = QtWidgets.QCheckBox(self.groupBox_2)
        self.cachingEnabled.setObjectName("cachingEnabled")
        self.horizontalLayout_6.addWidget(self.cachingEnabled)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.languageLabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.languageLabel.sizePolicy().hasHeightForWidth())
        self.languageLabel.setSizePolicy(sizePolicy)
        self.languageLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.languageLabel.setObjectName("languageLabel")
        self.horizontalLayout_5.addWidget(self.languageLabel)
        self.languageBox = QtWidgets.QComboBox(self.groupBox_2)
        self.languageBox.setObjectName("languageBox")
        self.horizontalLayout_5.addWidget(self.languageBox)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.switchPage)
        self.annotationsPage = QtWidgets.QWidget()
        self.annotationsPage.setObjectName("annotationsPage")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.annotationsPage)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.annotationsPage)
        self.tabWidget.setObjectName("tabWidget")
        self.textTab = QtWidgets.QWidget()
        self.textTab.setObjectName("textTab")
        self.tabWidget.addTab(self.textTab, "")
        self.imageTab = QtWidgets.QWidget()
        self.imageTab.setObjectName("imageTab")
        self.tabWidget.addTab(self.imageTab, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.annotationsPage)
        self.aboutPage = QtWidgets.QWidget()
        self.aboutPage.setObjectName("aboutPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.aboutPage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.aboutBox = QtWidgets.QTextBrowser(self.aboutPage)
        self.aboutBox.setOpenExternalLinks(True)
        self.aboutBox.setOpenLinks(False)
        self.aboutBox.setObjectName("aboutBox")
        self.gridLayout_6.addWidget(self.aboutBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.aboutPage)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_10.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_10.addWidget(self.cancelButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.groupBox.setTitle(_translate("Dialog", "Library"))
        self.refreshLibrary.setText(_translate("Dialog", "Startup: Refresh library"))
        self.fileRemember.setText(_translate("Dialog", "Remember open files"))
        self.coverShadows.setText(_translate("Dialog", "Cover shadows"))
        self.performCulling.setToolTip(_translate("Dialog", "Enabling reduces startup time and memory usage"))
        self.performCulling.setText(_translate("Dialog", "Load covers only when needed"))
        self.label.setToolTip(_translate("Dialog", "Restart application to see changes"))
        self.label.setText(_translate("Dialog", "Icon theme: "))
        self.darkIconsRadio.setToolTip(_translate("Dialog", "Restart application to see changes"))
        self.darkIconsRadio.setText(_translate("Dialog", "&Dark"))
        self.lightIconsRadio.setToolTip(_translate("Dialog", "Restart application to see changes"))
        self.lightIconsRadio.setText(_translate("Dialog", "L&ight"))
        self.autoTags.setText(_translate("Dialog", "Generate tags from files"))
        self.groupBox_2.setTitle(_translate("Dialog", "Reading"))
        self.hideScrollBars.setToolTip(_translate("Dialog", "Horizontal scrolling with Alt + Scroll\n"
"Reopen book to see changes"))
        self.hideScrollBars.setText(_translate("Dialog", "Hide scrollbars when reading"))
        self.cachingEnabled.setToolTip(_translate("Dialog", "Greatly reduces page transition time at the cost of more memory"))
        self.cachingEnabled.setText(_translate("Dialog", "Cache comic / pdf pages"))
        self.languageLabel.setText(_translate("Dialog", "Dictionary language:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.textTab), _translate("Dialog", "Text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imageTab), _translate("Dialog", "Comic/PDF"))
        self.okButton.setText(_translate("Dialog", "Scan Library"))
        self.cancelButton.setText(_translate("Dialog", "Close"))

